### ISSUE TITLE
Unix sockets not supported on this platform

### ISSUE THREAD

**Issue by Shaker-Hamdi** [TheWidlarzGroup/JWTAuthBackend#4]
After following all the steps, I ran `yarn dev` and I got this error ...

```
$ yarn dev
yarn run v1.22.17
$ ts-node-dev -r tsconfig-paths/register src/index.ts
Using ts-node version 8.10.2, typescript version 4.1.3
(node:14548) UnhandledPromiseRejectionWarning: Error: Error: 
Invalid `prisma.queryRaw()` invocation:


  Unix sockets not supported on this platform
    at C:\Users\shake\Desktop\www\JWTAuthBackend\src\index.ts:65:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting 
a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.50s.
```

**Comment by Shaker-Hamdi** [comment]
I'd really appreciate any help here. I tried to search for this error but with no luck. I'm stuck.

**Comment by maks-plotnikoff** [comment]
I have the same problem @jakex7@Nsquik

**Comment by rajesh-vishwa** [comment]
I have same problem.. 
```

> AuthBE@1.0.0 dev
> ts-node-dev -r tsconfig-paths/register src/index.ts

Using ts-node version 8.10.2, typescript version 4.1.3
(node:9894) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
/usr/local/bin/node[9894]: ../src/node_http_parser.cc:542:static void node::(anonymous namespace)::Parser::Initialize(const FunctionCallbackInfo<v8::Value> &): Assertion `args[3]->IsInt32()' failed.
 1: 0x109255025 node::Abort() [/usr/local/bin/node]
 2: 0x109254e61 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 3: 0x109270f4f node::(anonymous namespace)::Parser::Initialize(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x109426948 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 5: 0x109426416 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x109425b4f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x109c87a99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
```
